/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AllEvent: typeof import('./src/components/AllEvent.vue')['default']
    Asides: typeof import('./src/components/Asides.vue')['default']
    AutumnFloor: typeof import('./src/views/floor/AutumnFloor.vue')['default']
    Banner: typeof import('./src/views/layout/banner.vue')['default']
    CommonFloor: typeof import('./src/views/floor/CommonFloor.vue')['default']
    Double12F: typeof import('./src/views/floor/Double12F.vue')['default']
    DoubleFloor: typeof import('./src/views/floor/DoubleFloor.vue')['default']
    FloorComponent: typeof import('./src/views/floor/FloorComponent.vue')['default']
    GreenFloor: typeof import('./src/views/floor/GreenFloor.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ListD: typeof import('./src/views/layout/listD.vue')['default']
    ListF: typeof import('./src/views/layout/listF.vue')['default']
    ListFCoverflow: typeof import('./src/views/layout/listFCoverflow.vue')['default']
    ListH: typeof import('./src/views/layout/listH.vue')['default']
    ListM: typeof import('./src/views/layout/listM.vue')['default']
    Mobile: typeof import('./src/views/layout/mobile.vue')['default']
    Mobile2: typeof import('./src/views/layout/mobile2.vue')['default']
    Mobile3: typeof import('./src/views/layout/mobile3.vue')['default']
    MobileAi: typeof import('./src/views/layout/mobileAi.vue')['default']
    MobileW: typeof import('./src/views/layout/mobileW.vue')['default']
    TabContent: typeof import('./src/components/TabContent.vue')['default']
    Tabs: typeof import('./src/components/Tabs.vue')['default']
    XmasFloor: typeof import('./src/views/floor/XmasFloor.vue')['default']
  }
}
